// Privacy policy + terms of use, shown in-app (landing footer and
// Settings → Account). Content mirrors what the app actually does — update it
// whenever a new data flow ships.
import React from "react";
import { useFocusTrap } from "./a11y.js";

export const LEGAL_CONTACT = "andor.danse@gmail.com";

const PRIVACY = [
  ["What Peer stores", [
    "Your account basics: name, email address, and which sign-in method you used.",
    "Your study content: chats with the tutor, projects and uploaded study materials, notes, flashcard decks and review history, study-room messages, tracked concepts, and earned badges.",
    "Usage metering: a daily count of AI tokens your account used, so free and Pro limits work. We do not keep advertising profiles or behavioural trackers.",
  ]],
  ["Where it lives", [
    "On your device first: everything is stored locally (IndexedDB) so Peer works offline.",
    "If you sign in, the same content syncs to our database (Supabase/PostgreSQL, EU-hostable), protected so that only your account can read your rows (row-level security on every table).",
    "Guest mode keeps everything on the device only — nothing leaves it except the AI requests below.",
  ]],
  ["AI processing", [
    "When you ask the tutor something, the relevant conversation and study context is sent to our AI provider (Anthropic) to generate the answer, over an encrypted connection from our server — API keys never reach your browser.",
    "Document search uses an embeddings provider (Voyage AI) to index text you upload; generated diagrams use an image provider (fal.ai).",
    "We do not use your content to train models, and we send providers only what a feature needs.",
  ]],
  ["Your rights", [
    "Export: download everything as JSON anytime (Settings → Data → Export your data).",
    "Delete: remove your account and all cloud data in one click (Settings → Account → Danger zone). Local data stays on your device until you reset it.",
    `Questions or requests: ${LEGAL_CONTACT}.`,
  ]],
];

const TERMS = [
  ["The service", [
    "Peer is an adaptive AI study partner. Answers are generated by AI and can be wrong — verify anything that matters (exams, health, legal, finance).",
    "Free accounts include a daily AI allowance; Pro raises the limits. Limits are enforced server-side and reset at your local midnight.",
  ]],
  ["Fair use", [
    "One account per person; keep your login to yourself.",
    "Don't abuse the service: no attempts to exceed limits, extract keys, attack the infrastructure, or use Peer to produce harmful content.",
    "Study rooms are shared spaces — be decent to your study partners.",
  ]],
  ["Your content", [
    "Your study content stays yours. We claim no ownership and use it only to run the features you invoke.",
    "You're responsible for having the right to upload the materials you add.",
  ]],
  ["Subscriptions & changes", [
    "Paid plans (when available) are billed through Stripe; card details never touch our servers. Cancel anytime — access runs to the end of the paid period.",
    "We may update these terms as Peer evolves; material changes will be announced in-app.",
    `Contact: ${LEGAL_CONTACT}.`,
  ]],
];

export function LegalDialog({ kind, onClose }) {
  const trapRef = useFocusTrap(true, { onEscape: onClose });
  const sections = kind === "terms" ? TERMS : PRIVACY;
  const title = kind === "terms" ? "Terms of use" : "Privacy policy";

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <section
        ref={trapRef}
        className="modal legal-modal"
        role="dialog"
        aria-modal="true"
        aria-label={title}
        onClick={(event) => event.stopPropagation()}
      >
        <header className="legal-head">
          <h2>{title}</h2>
          <button className="icon-button" onClick={onClose} aria-label="Close" data-autofocus>✕</button>
        </header>
        <div className="legal-body">
          <p className="legal-updated">Last updated: July 5, 2026</p>
          {sections.map(([heading, points]) => (
            <div key={heading} className="legal-section">
              <h3>{heading}</h3>
              <ul>
                {points.map((point) => <li key={point.slice(0, 40)}>{point}</li>)}
              </ul>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}

// GDPR-style export: the local state IS the complete dataset (offline-first;
// the cloud holds a mirror of these same rows), so serializing it covers
// everything Peer knows about the user. No tokens/secrets live in state.
export function downloadDataExport(state) {
  const payload = {
    app: "Peer",
    format: "peer-data-export",
    version: 1,
    exportedAt: new Date().toISOString(),
    account: state.account || null,
    data: state,
  };
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `peer-data-export-${new Date().toISOString().slice(0, 10)}.json`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
